# Generated by Django 3.1.5 on 2021-01-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('b_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=100)),
                ('observation', models.CharField(max_length=280)),
            ],
        ),
    ]
