# Generated by Django 3.1.5 on 2021-01-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auser',
            name='observation',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
